# Generated by Django 5.2.8 on 2025-11-20 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.TextField()),
                ('email', models.TextField(unique=True)),
                ('password_hash', models.TextField()),
                ('tipo', models.TextField()),
            ],
            options={
                'db_table': 'usuarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Libro',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('titulo', models.TextField()),
                ('autor', models.TextField()),
                ('genero', models.TextField()),
                ('año', models.IntegerField()),
                ('cantidad', models.IntegerField()),
                ('isbn', models.TextField(unique=True)),
            ],
            options={
                'db_table': 'libros',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Prestamo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('dias', models.IntegerField()),
                ('fch_prestamo', models.DateField()),
                ('fch_devolucion', models.DateField()),
            ],
            options={
                'db_table': 'prestamos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
            ],
            options={
                'db_table': 'admin',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bibliotecario',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('universidad', models.TextField()),
            ],
            options={
                'db_table': 'bibliotecarios',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Universitario',
            fields=[
                ('usuario', models.OneToOneField(db_column='usuario_id', on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.usuario')),
                ('universidad', models.TextField()),
            ],
            options={
                'db_table': 'universitarios',
                'managed': False,
            },
        ),
    ]
